version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: teddy_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - teddy_postgres_data:/var/lib/postgresql/data

volumes:
  teddy_postgres_data:
